package sas

import "database/sql"

type Sasform struct {
	Id                         int            `json:"id"`
	Id_Usuario                 int            `json:"id_usuario"`
	Id_Estado                  int            `json:"id_estado"`
	Razon_Social               sql.NullString `json:"razon_social"`
	Provincia                  sql.NullString `json:"provincia"`
	Localidad                  sql.NullString `json:"localidad"`
	Calle                      sql.NullString `json:"calle"`
	Altura                     sql.NullString `json:"altura"`
	Piso                       sql.NullString `json:"piso"`
	Depto                      sql.NullString `json:"depto"`
	Num_Sede                   sql.NullString `json:"num_sede"`
	Duracion                   sql.NullString `json:"duracion"`
	Peso_Num                   *int           `json:"peso_num"`
	Porcintegr                 *int           `json:"porcintegr"`
	Fecha_Presentacion         sql.NullString `json:"fecha_presentacion"`
	Fecha_Aprobacion           sql.NullString `json:"fecha_aprobacion"`
	Block                      int            `json:"block"`
	Created_At                 sql.NullString `json:"created_at"`
	Updated_At                 sql.NullString `json:"updated_at"`
	Monto_Minimo               *bool          `json:"monto_minimo"`
	Estatuto_Modelo            *bool          `json:"estatuto_modelo"`
	Fecha_Firma                sql.NullString `json:"fecha_firma"`
	Fecha_Cierre_Fiscal        sql.NullString `json:"fecha_cierre_fiscal"`
	Lugar_Firma                sql.NullString `json:"lugar_firma"`
	Tipo_Instrumento           sql.NullString `json:"tipo_instrumento"`
	Fecha_Baja                 sql.NullString `json:"fecha_baja"`
	Fecha_Rechazo              sql.NullString `json:"fecha_rechazo"`
	Fecha_A_Presentar          sql.NullString `json:"fecha_a_presentar"`
	Entidad_Certif             sql.NullString `json:"entidad_certif"`
	Bloqueado                  bool           `json:"bloqueado"`
	Actividad                  sql.NullString `json:"actividad"`
	Email                      sql.NullString `json:"email"`
	Telefono                   sql.NullString `json:"telefono"`
	Completo                   *bool          `json:"completo"`
	Fecha_Rentas               sql.NullString `json:"fecha_rentas"`
	Fecha_Boletin              sql.NullString `json:"feacha_boletin"`
	Nro_Expediente             sql.NullString `json:"nro_expediente"`
	Cbu                        sql.NullString `json:"cbu"`
	Nro_Cta_Bco                sql.NullString `json:"nro_cta_bco"`
	Firmado                    int            `json:"firmado"`
	Actividad_Afip             sql.NullString `json:"actividad_afip"`
	Motivo_Rechazo             sql.NullString `json:"motivo_rechazo"`
	Entidad_Rechazante         sql.NullString `json:"entidad_rechazante"`
	Pago_Aranceles             bool           `json:"pago_aranceles"`
	Pago_Integracion_Capitales bool           `json:"pago_integracion_capitales"`
	Doc_Escribano_Subido       *bool          `json:"doc_escribano_subido"`
	Fecha_Ultimo_Pago          sql.NullString `json:"fecha_ultimo_pago"`
	Digitalizado               sql.NullString `json:"Digitalizado"`
	Cuit                       sql.NullString `json:"cuit"`
	Impuesto_Nac               sql.NullString `json:"impuesto_nac"`
	Sucursal_Banco             sql.NullString `json:"sucursal_banco"`
	Solicitar_Banco            sql.NullString `json:"solicitar_banco"`
	Archivo_Rentas             sql.NullString `json:"archivo_rentas"`
	Expediente_Ciudadano       bool           `json:"expediente_ciudadano"`
	Convenio_Rentas            sql.NullString `json:"convenio_rentas"`
	Comprobante_Integracion    bool           `json:"comprobante_integracion"`
	Puede_Publicar             bool           `json:"puede_publicar"`
	Fecha_Retiros_Doc          sql.NullString `json:"fecha_retiros_doc"`
	Envio_Mail_Sas_fin         sql.NullString `json:"envio_mail_sas_fin"`
	Papelera                   int            `json:"papelera"`
	Objeto_Societario          sql.NullString `json:"objeto_societario"`
	Baja_En_Afip               sql.NullString `json:"baja_en_afip"`
	Baja_En_Rentas             sql.NullString `json:"baja_en_rentas"`
	Ultimo_Balance             sql.NullString `json:"ultimo_balance"`
	Baja_Status                *int           `json:"baja_status"`
	Baja_Msg                   sql.NullString `json:"baja_msg"`
}
