package sas

type Sasform struct {
	Id                         int     `json:"id"`
	Id_Usuario                 int     `json:"id_usuario"`
	Id_Estado                  int     `json:"id_estado"`
	Razon_Social               *string `json:"razon_social"`
	Provincia                  *string `json:"provincia"`
	Localidad                  *string `json:"localidad"`
	Calle                      *string `json:"calle"`
	Altura                     *string `json:"altura"`
	Piso                       *string `json:"piso"`
	Depto                      *string `json:"depto"`
	Num_Sede                   *string `json:"num_sede"`
	Duracion                   *string `json:"duracion"`
	Peso_Num                   *int    `json:"peso_num"`
	Porcintegr                 *int    `json:"porcintegr"`
	Fecha_Presentacion         *string `json:"fecha_presentacion"`
	Fecha_Aprobacion           *string `json:"fecha_aprobacion"`
	Block                      int     `json:"block"`
	Created_At                 *string `json:"created_at"`
	Updated_At                 *string `json:"updated_at"`
	Monto_Minimo               *bool   `json:"monto_minimo"`
	Estatuto_Modelo            *bool   `json:"estatuto_modelo"`
	Fecha_Firma                *string `json:"fecha_firma"`
	Fecha_Cierre_Fiscal        *string `json:"fecha_cierre_fiscal"`
	Lugar_Firma                *string `json:"lugar_firma"`
	Tipo_Instrumento           *string `json:"tipo_instrumento"`
	Fecha_Baja                 *string `json:"fecha_baja"`
	Fecha_Rechazo              *string `json:"fecha_rechazo"`
	Fecha_A_Presentar          *string `json:"fecha_a_presentar"`
	Entidad_Certif             *string `json:"entidad_certif"`
	Bloqueado                  bool    `json:"bloqueado"`
	Actividad                  *string `json:"actividad"`
	Email                      *string `json:"email"`
	Telefono                   *string `json:"telefono"`
	Completo                   *bool   `json:"completo"`
	Fecha_Rentas               *string `json:"fecha_rentas"`
	Fecha_Boletin              *string `json:"feacha_boletin"`
	Nro_Expediente             *string `json:"nro_expediente"`
	Cbu                        *string `json:"cbu"`
	Nro_Cta_Bco                *string `json:"nro_cta_bco"`
	Firmado                    int     `json:"firmado"`
	Actividad_Afip             *string `json:"actividad_afip"`
	Motivo_Rechazo             *string `json:"motivo_rechazo"`
	Entidad_Rechazante         *string `json:"entidad_rechazante"`
	Pago_Aranceles             bool    `json:"pago_aranceles"`
	Pago_Integracion_Capitales bool    `json:"pago_integracion_capitales"`
	Doc_Escribano_Subido       *bool   `json:"doc_escribano_subido"`
	Fecha_Ultimo_Pago          *string `json:"fecha_ultimo_pago"`
	Digitalizado               *string `json:"Digitalizado"`
	Cuit                       *string `json:"cuit"`
	Impuesto_Nac               *string `json:"impuesto_nac"`
	Sucursal_Banco             *string `json:"sucursal_banco"`
	Solicitar_Banco            *string `json:"solicitar_banco"`
	Archivo_Rentas             *string `json:"archivo_rentas"`
	Expediente_Ciudadano       bool    `json:"expediente_ciudadano"`
	Convenio_Rentas            *string `json:"convenio_rentas"`
	Comprobante_Integracion    bool    `json:"comprobante_integracion"`
	Puede_Publicar             bool    `json:"puede_publicar"`
	Fecha_Retiros_Doc          *string `json:"fecha_retiros_doc"`
	Envio_Mail_Sas_fin         *string `json:"envio_mail_sas_fin"`
	Papelera                   int     `json:"papelera"`
	Objeto_Societario          *string `json:"objeto_societario"`
	Baja_En_Afip               *string `json:"baja_en_afip"`
	Baja_En_Rentas             *string `json:"baja_en_rentas"`
	Ultimo_Balance             *string `json:"ultimo_balance"`
	Baja_Status                *int    `json:"baja_status"`
	Baja_Msg                   *string `json:"baja_msg"`
}
